import { readFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Server-side view of the hash-pinned script library.
 *
 * The executor refuses any signed_script dispatch that arrives without a
 * scriptSha256 (apps/agent-node/src/exec/executor.ts) — deliberately, since
 * the dispatch-side hash is what lets the agent detect a request tampered
 * with in transit. So every caller must supply one, and reading it from the
 * manifests is the only way to get it right: hardcoding hashes here would
 * mean every script edit silently breaks dispatch until someone remembers
 * to update two places.
 *
 * Loaded once at startup. The manifests are generated by
 * packages/scripts/generate-manifests.ts and committed alongside the .ps1
 * files, so they are present in any deployment that ships the repo.
 */

export interface ScriptEntry {
  scriptId: string;
  name: string;
  category: string;
  tier: string;
  version: string;
  sha256: string;
  timeoutSeconds: number;
}

function locateLibrary(): string | null {
  const here = dirname(fileURLToPath(import.meta.url));
  const candidates = [
    process.env.SENTINEL_SCRIPTS_DIR,
    // running from src/ via tsx
    join(here, "..", "..", "..", "..", "packages", "scripts", "library"),
    // running from dist/
    join(here, "..", "..", "..", "..", "..", "packages", "scripts", "library"),
    join(process.cwd(), "packages", "scripts", "library"),
  ].filter((p): p is string => Boolean(p));

  return candidates.find((p) => existsSync(p)) ?? null;
}

function load(): Map<string, ScriptEntry> {
  const dir = locateLibrary();
  const registry = new Map<string, ScriptEntry>();

  if (!dir) {
    console.warn("[script-registry] script library not found — signed_script dispatch will be unavailable. Set SENTINEL_SCRIPTS_DIR.");
    return registry;
  }

  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".manifest.json")) continue;
    try {
      const m = JSON.parse(readFileSync(join(dir, file), "utf-8"));
      registry.set(m.scriptId, {
        scriptId: m.scriptId,
        name: m.name,
        category: m.category,
        tier: m.tier,
        version: m.version,
        sha256: m.sha256,
        timeoutSeconds: m.timeoutSeconds,
      });
    } catch (err) {
      console.error(`[script-registry] skipping malformed manifest ${file}:`, (err as Error).message);
    }
  }

  console.log(`[script-registry] loaded ${registry.size} scripts from ${dir}`);
  return registry;
}

const REGISTRY = load();

export function getScript(scriptId: string): ScriptEntry | null {
  return REGISTRY.get(scriptId) ?? null;
}

export function listScripts(): ScriptEntry[] {
  return [...REGISTRY.values()];
}
